Moving update in comment option from process argumento into config file.
twotired/jiralert pull request #1
Opened 2023-06-23 13:31 UTC by cropalato

I really like that feature, thanks for your PR, But I agree with @MytkoEnko ( https://github.com/prometheus-community/jiralert/pull/161#issuecomment-1580800245 ). Should be more flexible if we use config file to manage that.
So, here is my 2 cents...

2023-07-04 20:35 UTC, twotired requested changes
there are just a couple minor issues but otherwise LGTM

2023-07-04 20:35 UTC, twotired commented on pkg/config/config.go
> +	// Flag to auto-resolve opened issue when the alert is resolved.
this should be "// Flag to enable updates in comments"

2023-07-04 20:35 UTC, twotired commented on pkg/config/config_test.go
> +    } else if name == "UpdateInComment" {
indentation appears inconsistent

2023-07-06 12:31 UTC, cropalato commented
Fixing small issues:

- Adding '//' flag to enable updates in comments
- Fixing indentation

2023-07-06 12:43 UTC, cropalato commented
Fixed.

2023-07-19 15:28 UTC, cropalato commented
@twotired Do you want me to change something else?

2023-07-20 04:30 UTC, merged